spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  cloud:
    gateway:
      routes:
        - id: GestionCoursFormateur
          uri: lb://GestionCoursFormateur
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*) , /${path}
        - id: GestionFormateur
          uri: lb://GestionFormateur
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*) , /${path}
